service: index-factory

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  tableName: 'index-factory-table-${self:provider.stage}'
  wsgi:
    app: app.handler
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    stages:
      - local
    start:
      migrate: true

provider:
  name: aws
  runtime: python3.6
  stage: local
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["IndexFactoryDynamoDBTable", "Arn" ] }
  environment:
    INDEX_FACTORY_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    IndexFactoryDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: indexCode
            AttributeType: S
        KeySchema:
          -
            AttributeName: indexCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

plugins:
  - serverless-dynamodb-local
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline  # should be last in list

